### ISSUE TITLE
Source-only model

### ISSUE THREAD

**Issue by kailigo** [xuyu0010/ATCoN#1]
Hi Authors. Thanks for the excellent work. Could you please share your source-only models that are trained with source datasets. Thanks  a lot.

**Comment by kailigo** [comment]
A follow-up question: I loaded the provided checkpoint (the one you called as "demo weight") for the target domain, evaluated it on the HMDB51 dataset, and got a top-1 acc 0.745, which is lower than the reported 0.79. I got same results with PyTorch versions 1.10.0 and 1.8.0 where version 1.8.0 is your suggested version. I am wondering if you have any thought on the performance discrepancy. Thanks a lot.

**Comment by xuyu0010** [comment]
Hi Kai,

Thank you for your interest in our work. We will include the source-only models shortly and thank you very much for your reminder. We will start off with the models from H-U as it is the most commonly used benchmark. We will include other source-only models subsequently.

As for the top-1 acc, it seems quite strange. I will include the training logs in the exps folder and the testing logs in the test folder as soon as possible so that you may compare if there is anything different.

**Comment by xuyu0010** [comment]
Hi Kai,

The logs are now uploaded and you may compare your testing log with mine and see the difference. One possible factor that may indeed cause a lower score is that your cudnn may not be installed/may not be installed correctly. There will not be errors reported even if cudnn is not available (at least according to my experience) but it will cause a notable discrepancy even with the same weight tested.

**Comment by kailigo** [comment]
Hi Yuecong, 

Thanks for the prompt action. I roughly compare your logs and mine, and find that you load 

> Only model state resumed from: `./../exps/models/V-SftDA_ep-0020.pth'

The name of the checkpoint is different from the Google Drive one. Also, the logs show you performs the evaluation half a year ago. I am wondering if the two models are the same. 

I will check more details soon and also verify if cudnn is the reason. Thanks a lot.

**Comment by xuyu0010** [comment]
Hi Kai,

Yes they are the same. I have accidentally mistaken the number of epochs needed for the H-U (or U-H, the same) dataset so my re-naming of the demo weight file was incorrect. If you are unsure, you may re-download the file again. The epochs needed for the three datasets are a bit different.

The evaluation is indeed performed half a year ago, we actually completed the whole project end Feb, ECCV ddl was early March, so no surprise :). Do check for more details and verify if cudnn is the reason. Feel free to contact me if you have further questions.

**Comment by kailigo** [comment]
Hi Yuecong,

I came to work on this project again after diverting to another project for a while. Sorry to bother you again. 

You mentioned that the cause for the performance discrepancy could be cudnn, but according to this discussion
https://discuss.pytorch.org/t/how-to-check-if-torch-uses-cudnn/21933/4 
The common Pytorch installation automatically include many library dependencies (including cudnn).
My previous personal experience also aligns with this discussion. 

I am wondering if it is possible for you to test the provided "demo weight" on your machine again, and eliminate the possibility that a wrong checkpoint was uploaded (the project was done a long time ago, after all). 

If you indeed find that the "demo weight" is the right checkpoint, could you please provide the configurations of you environment, e.g., using 

`conda env export > environment.yml`

if you are using conda to manage your virtual environments. Or other equivalent ways. 

Thanks a lot for your help.

**Comment by xuyu0010** [comment]
Hi Kai,

Thank you very much for the suggestion! However, I am currently not able to access the machine used for this project freely so I am sorry that I am unable to guarantee when could the yml file be uploaded :(. I will update this repo as soon as possible when I can export the exact environment for reference 👍 .

Thanks a lot for your support!

**Comment by kailigo** [comment]
Hi Yuecong,

Thanks for the prompt reply. 

May I ask if it is possible for you to run the "demo weight" on your machine that is current available and see if the results can be reproduced. If you got similar results as mine, that implies the environment really accounts for this. Thanks a lot.   

Best,
Kai
