### ISSUE TITLE
About the pretrain model

### ISSUE THREAD

**Issue by kou35** [xuyu0010/ATCoN#2]
I want to know where to get the pretrain model "pretrained/tsn2d_rgb_r50.pth". And the code in the file train_source_model.py, there is two parameter “end_epoch” in the function train_source_model.

**Comment by xuyu0010** [comment]
> I want to know where to get the pretrain model "pretrained/tsn2d_rgb_r50.pth". And the code in the file train_source_model.py, there is two parameter “end_epoch” in the function train_source_model.

Hi! Thank you for your interest in our project.
I would also like to thank you for pointing out the repeated parameter, that has been fixed and you may renew your repository by simply pulling again. Sorry for the confusion.
As for the pretrained model, it is uploaded in Google Drive. Please see the README (https://github.com/xuyu0010/ATCoN#notes-on-training-and-testing) for details.

**Comment by kou35** [comment]
Thank you so much.
