### ISSUE TITLE
a coding problem

### ISSUE THREAD

**Issue by kou35** [xuyu0010/ATCoN#5]
The coding here(https://github.com/xuyu0010/ATCoN/blob/0c7496fb61c1a99551535cb1d8c5dbdc89f97e29/network/ATCoN.py#L142) may be wrong. I get higher result after change it.

**Comment by xuyu0010** [comment]
Hi, thank you very much for your suggestion, maybe you could send me your code and maybe I check against mine? Thank you!

**Comment by kou35** [comment]
i think it is out = x[:, :, i, :, :]

**Comment by xuyu0010** [comment]
> i think it is out = x[:, :, i, :, :]

Hi, thank you very much for pointing it out! Yes, it was found out that this line was modified for our own testing and visualization, and forgot to reverse back. Thank you! The code is now fixed.
