### ISSUE TITLE
Sports1M dataset issue

### ISSUE THREAD

**Issue by wj-son** [xuyu0010/ATCoN#6]
Thanks for your great work.
I've been downloading DA datasets for implementing your work.
There is no problem except for downloading and extracting the Sports1M dataset.
Downloaded from Google drive, it must be some parted zip data.
So, do other parts of the dataset exists?

**Comment by xuyu0010** [comment]
Hi Son,

Thank you for your interest! However, I am unsure if you have downloaded the Sports1M dataset (for Sports-DA) correctly. We did not provide any Google Drive link for Sports1M. If you are unable to download from the original website https://cs.stanford.edu/people/karpathy/deepvideo/, consider downloading Sports1M at https://xuyu0010.github.io/msvda.html#data-download.
